version: '3'

volumes:
  data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    image: nastyapan98/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: nastyapan98/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: nastyapan98/foodgram_nginx
    volumes:
      - static:/static/
      - media:/app/media
    # env_file: ../.env
    ports:
      - 8000:80
