# Generated by Django 3.2.16 on 2024-02-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_backend', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='receipt',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='receipt',
            new_name='recipe',
        ),
    ]
