# Generated by Django 3.2.16 on 2024-03-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_backend', '0005_auto_20240324_0930'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_and_author'),
        ),
    ]
