# Generated by Django 3.2.16 on 2024-02-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='foodgram_backend/', verbose_name='Фото'),
        ),
    ]
