# Generated by Django 3.2.16 on 2024-03-25 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240323_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^(?!.*@)+(?!me$)[a-zA-Z0-9_]+$')], verbose_name='Логин'),
        ),
    ]
